import { useLetterhead, Letterhead, PrintableOverlay, DocFooterNote } from "../../lib/printable";

export default function ImagingReportPrint({ study, release, onClose, actor }) {
  const settings = useLetterhead();

  return (
    <PrintableOverlay title={`Imaging report — ${study.name}`} onClose={onClose} actor={actor} docType="imaging report" docRef={study.accession} patientName={study.patientName}>
      <Letterhead settings={settings} />

      <div style={docTitle}>{study.modality.toUpperCase()} REPORT</div>

      <table style={metaTable}>
        <tbody>
          <tr><td style={metaLabel}>Patient</td><td style={metaVal}>{study.patientName}</td>
              <td style={metaLabel}>Hospital No.</td><td style={metaVal}>{study.hospitalNo}</td></tr>
          <tr><td style={metaLabel}>Study</td><td style={metaVal}>{study.name}</td>
              <td style={metaLabel}>Accession</td><td style={{ ...metaVal, fontFamily: "monospace" }}>{study.accession}</td></tr>
          <tr><td style={metaLabel}>Modality</td><td style={metaVal}>{study.modality}</td>
              <td style={metaLabel}>Requested</td><td style={metaVal}>{new Date(study.requestedAt).toLocaleString()}</td></tr>
          <tr><td style={metaLabel}>Priority</td><td style={{ ...metaVal, textTransform: "capitalize" }}>{study.priority}</td>
              <td style={metaLabel}>&nbsp;</td><td style={metaVal}>&nbsp;</td></tr>
        </tbody>
      </table>

      {Object.keys(study.tech || {}).length > 0 && (
        <div style={techBlock}>
          <b>Technical parameters:</b>{" "}
          {Object.entries(study.tech).map(([k, v]) => `${k}: ${v}`).join("  \u00b7  ")}
        </div>
      )}

      <div style={sectionLabel}>FINDINGS &amp; IMPRESSION</div>
      <div style={reportBox}>
        {study.urgentFinding && <div style={urgentFlag}>{"\u26a0"} Urgent finding</div>}
        <div style={reportText}>{study.report || "\u2014"}</div>
      </div>

      <div style={statusBlock}>
        <div><b>Status:</b> Reported</div>
        {release && (
          <>
            <div><b>Released by:</b> {release.releasedBy}</div>
            <div><b>Released:</b> {new Date(release.releasedAt).toLocaleString()}</div>
            {release.orderingClinician && <div><b>Ordering clinician:</b> {release.orderingClinician}</div>}
          </>
        )}
      </div>

      <DocFooterNote>
        This report was generated by HospitalOS and reflects findings reported by radiology staff at
        {" "}{settings?.hospitalName}. For clinical correlation, please discuss with the ordering clinician.
      </DocFooterNote>
    </PrintableOverlay>
  );
}

const docTitle = { fontSize: 13, fontWeight: 700, letterSpacing: "0.08em", color: "#7A8AA3", marginBottom: 14 };
const metaTable = { width: "100%", borderCollapse: "collapse", marginBottom: 16, fontSize: 12 };
const metaLabel = { padding: "4px 8px 4px 0", color: "#7A8AA3", fontWeight: 600, whiteSpace: "nowrap", width: "12%" };
const metaVal = { padding: "4px 16px 4px 0", color: "#22272B" };
const techBlock = { fontSize: 11.5, color: "#5A6472", background: "#F8FAFC", border: "1px solid #E4E9F2", borderRadius: 8, padding: "8px 12px", marginBottom: 16 };
const sectionLabel = { fontSize: 10.5, fontWeight: 700, letterSpacing: "0.06em", color: "#7A8AA3", marginBottom: 8, textTransform: "uppercase" };
const reportBox = { border: "1px solid #E4E9F2", borderRadius: 8, padding: "14px 16px", marginBottom: 20, minHeight: 100 };
const urgentFlag = { fontSize: 12, fontWeight: 700, color: "#B0281F", marginBottom: 8 };
const reportText = { fontSize: 12.5, lineHeight: 1.8, color: "#22272B", whiteSpace: "pre-wrap" };
const statusBlock = { fontSize: 12, color: "#22272B", lineHeight: 1.9, background: "#F8FAFC", border: "1px solid #E4E9F2", borderRadius: 8, padding: "12px 14px" };
