import { useLetterhead, Letterhead, PrintableOverlay, DocFooterNote } from "../../lib/printable";

const naira = (n) => "\u20a6" + Math.round(n).toLocaleString();

export default function ReceiptPrint({ payment, account, onClose, actor }) {
  const settings = useLetterhead();

  return (
    <PrintableOverlay title={`Receipt — ${payment.receipt}`} onClose={onClose} actor={actor} docType="receipt" docRef={payment.receipt} patientName={payment.patientName}>
      <Letterhead settings={settings} />

      <div style={docTitle}>PAYMENT RECEIPT</div>

      <table style={metaTable}>
        <tbody>
          <tr><td style={metaLabel}>Patient</td><td style={metaVal}>{payment.patientName}</td>
              <td style={metaLabel}>Hospital No.</td><td style={metaVal}>{payment.hospitalNo}</td></tr>
          <tr><td style={metaLabel}>Receipt No.</td><td style={{ ...metaVal, fontFamily: "monospace" }}>{payment.receipt}</td>
              <td style={metaLabel}>Date</td><td style={metaVal}>{new Date(payment.at).toLocaleString()}</td></tr>
          <tr><td style={metaLabel}>Method</td><td style={metaVal}>{payment.method}</td>
              <td style={metaLabel}>&nbsp;</td><td style={metaVal}>&nbsp;</td></tr>
        </tbody>
      </table>

      {account && account.charges?.length > 0 && (
        <>
          <div style={sectionLabel}>ACCOUNT CHARGES ON FILE</div>
          <table style={chargeTable}>
            <thead><tr><th style={th}>Source</th><th style={th}>Description</th><th style={{ ...th, textAlign: "right" }}>Amount</th></tr></thead>
            <tbody>
              {account.charges.map((c, i) => (
                <tr key={i}>
                  <td style={td}>{c.source}</td>
                  <td style={td}>{c.description}</td>
                  <td style={{ ...td, textAlign: "right", fontFamily: "monospace" }}>{naira(c.amount)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </>
      )}

      <div style={amountBlock}>
        <div style={amountLabel}>Amount paid</div>
        <div style={amountValue}>{naira(payment.amount)}</div>
        {account && (
          <div style={balanceLine}>
            Outstanding balance after this payment: <b>{naira(Math.max(0, account.balance - payment.amount))}</b>
          </div>
        )}
      </div>

      <DocFooterNote>
        This receipt was generated by HospitalOS on behalf of {settings?.hospitalName}. Please retain
        this document for your records. For queries, contact {settings?.phone} or {settings?.email}.
      </DocFooterNote>
    </PrintableOverlay>
  );
}

const docTitle = { fontSize: 13, fontWeight: 700, letterSpacing: "0.08em", color: "#7A8AA3", marginBottom: 14 };
const metaTable = { width: "100%", borderCollapse: "collapse", marginBottom: 18, fontSize: 12 };
const metaLabel = { padding: "4px 8px 4px 0", color: "#7A8AA3", fontWeight: 600, whiteSpace: "nowrap", width: "14%" };
const metaVal = { padding: "4px 16px 4px 0", color: "#22272B" };
const sectionLabel = { fontSize: 10.5, fontWeight: 700, letterSpacing: "0.06em", color: "#7A8AA3", marginBottom: 8, textTransform: "uppercase" };
const chargeTable = { width: "100%", borderCollapse: "collapse", fontSize: 12, marginBottom: 20 };
const th = { textAlign: "left", padding: "7px 10px", background: "#F4F6FA", borderBottom: "1.5px solid #22272B", fontSize: 10.5, textTransform: "uppercase", letterSpacing: "0.04em", color: "#5A6472" };
const td = { padding: "6px 10px", borderBottom: "1px solid #E4E9F2" };
const amountBlock = { background: "#F8FAFC", border: "1px solid #E4E9F2", borderRadius: 10, padding: "18px 20px", textAlign: "center", marginBottom: 10 };
const amountLabel = { fontSize: 11, fontWeight: 600, color: "#7A8AA3", textTransform: "uppercase", letterSpacing: "0.05em" };
const amountValue = { fontSize: 30, fontWeight: 700, color: "#1D7A4C", margin: "4px 0" };
const balanceLine = { fontSize: 12, color: "#5A6472", marginTop: 6 };
