import { getTest, flagValue } from "./labService";
import { useLetterhead, Letterhead, PrintableOverlay, DocFooterNote } from "../../lib/printable";

const FLAG_COLOR = { low: "#1E5A8A", high: "#A35A2E", critical: "#B0281F", normal: "#22272B" };

export default function LabReportPrint({ order, release, onClose, actor }) {
  const settings = useLetterhead();
  const test = getTest(order.testCode);

  return (
    <PrintableOverlay title={`Lab report — ${order.testName}`} onClose={onClose} actor={actor} docType="lab report" docRef={order.accession} patientName={order.patientName}>
      <Letterhead settings={settings} />

      <div style={docTitle}>LABORATORY REPORT</div>

      <table style={metaTable}>
        <tbody>
          <tr><td style={metaLabel}>Patient</td><td style={metaVal}>{order.patientName}</td>
              <td style={metaLabel}>Hospital No.</td><td style={metaVal}>{order.hospitalNo}</td></tr>
          <tr><td style={metaLabel}>Test</td><td style={metaVal}>{order.testName}</td>
              <td style={metaLabel}>Accession</td><td style={{ ...metaVal, fontFamily: "monospace" }}>{order.accession}</td></tr>
          <tr><td style={metaLabel}>Department</td><td style={metaVal}>{order.department}</td>
              <td style={metaLabel}>Ordered</td><td style={metaVal}>{new Date(order.orderedAt).toLocaleString()}</td></tr>
          {order.collectedAt && (
            <tr><td style={metaLabel}>Specimen</td><td style={metaVal}>{test?.specimen || "\u2014"}</td>
                <td style={metaLabel}>Collected</td><td style={metaVal}>{new Date(order.collectedAt).toLocaleString()}</td></tr>
          )}
        </tbody>
      </table>

      <table style={resultTable}>
        <thead>
          <tr>
            <th style={th}>Analyte</th><th style={th}>Result</th><th style={th}>Unit</th>
            <th style={th}>Reference range</th><th style={th}>Flag</th>
          </tr>
        </thead>
        <tbody>
          {test?.analytes.map((a) => {
            const val = order.results?.[a.key];
            const flag = val != null ? flagValue(order.testCode, a, val) : null;
            return (
              <tr key={a.key}>
                <td style={{ ...td, fontWeight: 600 }}>{a.label}</td>
                <td style={{ ...td, fontFamily: "monospace", color: flag ? FLAG_COLOR[flag] : "#22272B", fontWeight: flag === "critical" ? 700 : 400 }}>{val ?? "\u2014"}</td>
                <td style={td}>{a.unit || ""}</td>
                <td style={td}>{a.qualitative ? "\u2014" : `${a.low}\u2013${a.high}`}</td>
                <td style={{ ...td, color: flag ? FLAG_COLOR[flag] : "#7A8AA3", fontWeight: 600, textTransform: "capitalize" }}>{flag && flag !== "normal" ? flag : ""}</td>
              </tr>
            );
          })}
        </tbody>
      </table>

      <div style={statusBlock}>
        <div><b>Status:</b> {order.status === "verified" ? "Verified" : order.status}</div>
        {release && (
          <>
            <div><b>Released by:</b> {release.releasedBy}</div>
            <div><b>Released:</b> {new Date(release.releasedAt).toLocaleString()}</div>
            {release.orderingClinician && <div><b>Ordering clinician:</b> {release.orderingClinician}</div>}
          </>
        )}
      </div>

      <DocFooterNote>
        This report was generated by HospitalOS and reflects results verified by laboratory staff at
        {" "}{settings?.hospitalName}. For clinical correlation, please discuss with the ordering clinician.
      </DocFooterNote>
    </PrintableOverlay>
  );
}

const docTitle = { fontSize: 13, fontWeight: 700, letterSpacing: "0.08em", color: "#7A8AA3", marginBottom: 14 };
const metaTable = { width: "100%", borderCollapse: "collapse", marginBottom: 18, fontSize: 12 };
const metaLabel = { padding: "4px 8px 4px 0", color: "#7A8AA3", fontWeight: 600, whiteSpace: "nowrap", width: "12%" };
const metaVal = { padding: "4px 16px 4px 0", color: "#22272B" };
const resultTable = { width: "100%", borderCollapse: "collapse", fontSize: 12, marginBottom: 20 };
const th = { textAlign: "left", padding: "8px 10px", background: "#F4F6FA", borderBottom: "1.5px solid #22272B", fontSize: 10.5, textTransform: "uppercase", letterSpacing: "0.04em", color: "#5A6472" };
const td = { padding: "7px 10px", borderBottom: "1px solid #E4E9F2" };
const statusBlock = { fontSize: 12, color: "#22272B", lineHeight: 1.9, background: "#F8FAFC", border: "1px solid #E4E9F2", borderRadius: 8, padding: "12px 14px" };
